<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
	</PropertyGroup>
	
	<PropertyGroup Condition=" '$(Configuration)' != 'Debug' ">
		<DebugType>None</DebugType>
		<DebugSymbols>False</DebugSymbols>
	</PropertyGroup>

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Csis.CodeAnalyzers" Version="1.0.8">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Csis.Utilities" Version="1.11.11" />
	</ItemGroup>

</Project>
