<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>disable</Nullable>
		<Version>1.10.4</Version>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<Title>Admission</Title>
		<Authors>Mojtaba Zeraati</Authors>
		<Company>Csis</Company>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Csis.Abstractions" Version="1.4.15" />
		<PackageReference Include="Microsoft.AspNetCore.Http" Version="2.3.0" />
		<PackageReference Include="Microsoft.Extensions.Http" Version="9.0.10" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.10" />
		<PackageReference Include="Microsoft.Extensions.Options" Version="9.0.10" />
	</ItemGroup>

	<ItemGroup>
	  <Reference Include="Microsoft.Extensions.Logging.Abstractions">
	    <HintPath>C:\Program Files\dotnet\packs\Microsoft.AspNetCore.App.Ref\9.0.8\ref\net9.0\Microsoft.Extensions.Logging.Abstractions.dll</HintPath>
	  </Reference>
	</ItemGroup>

</Project>
