/* =========================================================
 * This file is part of the Csis.Template
 * Do not make any modifications on this file
 * All changes will be rejected in code review sessions
 * ========================================================= */

using Csis.Admission.Application.Common.Interfaces;
using Csis.Admission.Domain.Common;
using Csis.Utilities;
using System.Globalization;

namespace Csis.Admission.Services;

internal sealed class TrackingCodeService<TEntity>(
    IRepository<TEntity> repo,
    IDateTimeService dateTimeService) : ITrackingCodeService<TEntity> where TEntity : class, IEntity, ITrackableEntity
{
    private const int MaximumTriesCount = 15;
    private static readonly PersianCalendar _persianCalendar = new();

    public async Task<string> GetTrackingCodeAsync(Func<string> generator, CancellationToken cancellationToken = default) {
        ArgumentNullException.ThrowIfNull(generator);

        await Task.Delay(Random.Shared.Next(1, 30), cancellationToken);

        var trackingCode = string.Empty;
        var triesCount = 0;

        while ( true ) {
            // تولید کد رهگیری
            trackingCode = generator()?.Trim();

            if ( string.IsNullOrWhiteSpace(trackingCode) ) {
                throw new Exception("Invalid code generated by generator");
            }

            if ( trackingCode.Length < 6 ) {
                throw new Exception("Minimum length for tracking code is 6.");
            }

            if ( trackingCode.Length > 30 ) {
                throw new Exception("Maximum length for tracking code is 30.");
            }

            // بررسی تکراری نبودن کد رهگیری در جدول دیتابیس
            if ( !await repo.ExistsAsync(x => x.TrackingCode == trackingCode, cancellationToken: cancellationToken) ) {
                break;
            }

            triesCount++;

            if ( triesCount >= MaximumTriesCount ) {
                throw new Exception("Can't generate unique tracking code. Try again later");
            }
        }

        return trackingCode;
    }

    public async Task<string> GetRandomTrackingCodeAsync(int codeLength = 8, CancellationToken cancellationToken = default) {
        if ( codeLength < 6 ) {
            throw new ArgumentException("Minimum length for tracking code is 6.", nameof(codeLength));
        }

        if ( codeLength > 30 ) {
            throw new ArgumentException("Maximum length for tracking code is 30.", nameof(codeLength));
        }

        return await GetTrackingCodeAsync(() => {
            while ( true ) {
                var trackingCode = StringHelper.Random(codeLength, CharacterSet.Numeric);

                // جلوگیری از کد رهگیری که با 0 شروع شده باشد
                if ( trackingCode.StartsWith('0') ) {
                    continue;
                }

                return trackingCode;
            }
        }, cancellationToken);
    }

    public async Task<string> GetTimeBasedTrackingCodeAsync(CancellationToken cancellationToken = default) {
        return await GetTrackingCodeAsync(() => {
            var dateTime = dateTimeService.Now;

            // سال
            var year = _persianCalendar.GetYear(dateTime);
            // تعداد روز گذشته از ابتدای سال
            var dayOfYear = _persianCalendar.GetDayOfYear(dateTime).ToString().PadLeft(3, '0');
            // تعداد تیک گذشته از ابتدای روز
            var ticksInDay = (dateTime - dateTime.Date).Ticks.ToString().PadLeft(9, '0')[^9..];

            return $"{year}{dayOfYear}{ticksInDay}";
        }, cancellationToken);
    }
}
