//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Csis.Admission.Application.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Csis.Admission.Application.Common.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرزند خوانده.
        /// </summary>
        public static string AdoptedChild {
            get {
                return ResourceManager.GetString("AdoptedChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جامعه المصطفی العالمیه.
        /// </summary>
        public static string AlMustafaInternationalUniversity {
            get {
                return ResourceManager.GetString("AlMustafaInternationalUniversity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عربی.
        /// </summary>
        public static string Arabic {
            get {
                return ResourceManager.GetString("Arabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيمه نيروهاي مسلح.
        /// </summary>
        public static string ArmedForces {
            get {
                return ResourceManager.GetString("ArmedForces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ترجمه مقاله.
        /// </summary>
        public static string ArticleTranslation {
            get {
                return ResourceManager.GetString("ArticleTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ترجمه مقاله.
        /// </summary>
        public static string ArticleTranslationDuplicate {
            get {
                return ResourceManager.GetString("ArticleTranslationDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تالیف مقاله.
        /// </summary>
        public static string ArticleWriting {
            get {
                return ResourceManager.GetString("ArticleWriting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کارشناسی.
        /// </summary>
        public static string BachelorDegree {
            get {
                return ResourceManager.GetString("BachelorDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيمه بانک.
        /// </summary>
        public static string BankInsurance {
            get {
                return ResourceManager.GetString("BankInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تالیف کتاب.
        /// </summary>
        public static string BookWriting {
            get {
                return ResourceManager.GetString("BookWriting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرکز مدیریت برادران.
        /// </summary>
        public static string CenterForManagementOfIslamicSeminariesOfBrothersNationwide {
            get {
                return ResourceManager.GetString("CenterForManagementOfIslamicSeminariesOfBrothersNationwide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرکز مدیریت خواهران.
        /// </summary>
        public static string CenterForManagementOfIslamicSeminariesOfSistersNationwide {
            get {
                return ResourceManager.GetString("CenterForManagementOfIslamicSeminariesOfSistersNationwide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرزند.
        /// </summary>
        public static string Child {
            get {
                return ResourceManager.GetString("Child", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کمیسیون.
        /// </summary>
        public static string Commission {
            get {
                return ResourceManager.GetString("Commission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت موسسات فرهنگی.
        /// </summary>
        public static string CulturalInstitutions {
            get {
                return ResourceManager.GetString("CulturalInstitutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دبیرخانه شورای برنامه‌ریزی مدارس علوم دینی اهل سنت (طلاب اهل سنت).
        /// </summary>
        public static string DabirkhaneShoraMadresAhlSonnat {
            get {
                return ResourceManager.GetString("DabirkhaneShoraMadresAhlSonnat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دفاتر مراجع تقلید.
        /// </summary>
        public static string DafaterMaraje {
            get {
                return ResourceManager.GetString("DafaterMaraje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دفتر تبلیغات اسلامی حوزه علمیه.
        /// </summary>
        public static string DaftarTablighatEslamiHowze {
            get {
                return ResourceManager.GetString("DaftarTablighatEslamiHowze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عروس.
        /// </summary>
        public static string DaughterInLaw {
            get {
                return ResourceManager.GetString("DaughterInLaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طلاق همسر.
        /// </summary>
        public static string Divorced {
            get {
                return ResourceManager.GetString("Divorced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دکتری.
        /// </summary>
        public static string DoctoralDegree {
            get {
                return ResourceManager.GetString("DoctoralDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حجره یا خوابگاه.
        /// </summary>
        public static string Dormitory {
            get {
                return ResourceManager.GetString("Dormitory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اوقافی.
        /// </summary>
        public static string Endowment {
            get {
                return ResourceManager.GetString("Endowment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انگلیسی.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زن.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فوق دیپلم.
        /// </summary>
        public static string GraduateDiploma {
            get {
                return ResourceManager.GetString("GraduateDiploma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوه.
        /// </summary>
        public static string Grandchild {
            get {
                return ResourceManager.GetString("Grandchild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حافظین حدیث.
        /// </summary>
        public static string HadithMemorizers {
            get {
                return ResourceManager.GetString("HadithMemorizers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيمه خدمات درماني.
        /// </summary>
        public static string HealthServices {
            get {
                return ResourceManager.GetString("HealthServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خرید مسکن.
        /// </summary>
        public static string HomePurchase {
            get {
                return ResourceManager.GetString("HomePurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امام جماعت.
        /// </summary>
        public static string ImamJamaat {
            get {
                return ResourceManager.GetString("ImamJamaat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امام جماعت مدارس.
        /// </summary>
        public static string ImamJamaatMadarese {
            get {
                return ResourceManager.GetString("ImamJamaatMadarese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امام جمعه.
        /// </summary>
        public static string ImamJomeh {
            get {
                return ResourceManager.GetString("ImamJomeh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدمات.
        /// </summary>
        public static string Introduction {
            get {
                return ResourceManager.GetString("Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایرانی.
        /// </summary>
        public static string Iranian {
            get {
                return ResourceManager.GetString("Iranian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جامعه المصطفی العالمیه (طلاب غیرایرانی).
        /// </summary>
        public static string JameatAlMostafa {
            get {
                return ResourceManager.GetString("JameatAlMostafa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جامعه القرآن الکریم.
        /// </summary>
        public static string JameatAlQuran {
            get {
                return ResourceManager.GetString("JameatAlQuran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جامعه الزهرا س.
        /// </summary>
        public static string JameatAlZahra {
            get {
                return ResourceManager.GetString("JameatAlZahra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطبا خوزستان.
        /// </summary>
        public static string KhatabaKhuzestan {
            get {
                return ResourceManager.GetString("KhatabaKhuzestan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سطح چهار.
        /// </summary>
        public static string LevelFour {
            get {
                return ResourceManager.GetString("LevelFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سطح یک.
        /// </summary>
        public static string LevelOne {
            get {
                return ResourceManager.GetString("LevelOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سطح سه.
        /// </summary>
        public static string LevelThree {
            get {
                return ResourceManager.GetString("LevelThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سطح دو.
        /// </summary>
        public static string LevelTwo {
            get {
                return ResourceManager.GetString("LevelTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدارس امین.
        /// </summary>
        public static string MadreseAmin {
            get {
                return ResourceManager.GetString("MadreseAmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرد.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرکز مدیریت اصفهان.
        /// </summary>
        public static string ManagementCenterOfIslamicSeminariesOfIsfahan {
            get {
                return ResourceManager.GetString("ManagementCenterOfIslamicSeminariesOfIsfahan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرکز مدیریت خراسان.
        /// </summary>
        public static string ManagementCenterOfIslamicSeminariesOfKhorasan {
            get {
                return ResourceManager.GetString("ManagementCenterOfIslamicSeminariesOfKhorasan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرکز مدیریت حوزه‌های علمیه برادران سراسر کشور.
        /// </summary>
        public static string MarkazModiriyatHowzeBaradaran {
            get {
                return ResourceManager.GetString("MarkazModiriyatHowzeBaradaran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرکز مدیریت حوزه‌های علمیه اصفهان (طلاب خواهران و برادران).
        /// </summary>
        public static string MarkazModiriyatHowzeEsfahan {
            get {
                return ResourceManager.GetString("MarkazModiriyatHowzeEsfahan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرکز مدیریت حوزه‌های علمیه خواهران سراسر کشور.
        /// </summary>
        public static string MarkazModiriyatHowzeKhaharan {
            get {
                return ResourceManager.GetString("MarkazModiriyatHowzeKhaharan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرکز مدیریت حوزه‌های علمیه خراسان (طلاب خواهر و برادر).
        /// </summary>
        public static string MarkazModiriyatHowzeKhorasan {
            get {
                return ResourceManager.GetString("MarkazModiriyatHowzeKhorasan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرکز امور مساجد.
        /// </summary>
        public static string MarkazOmourMasajed {
            get {
                return ResourceManager.GetString("MarkazOmourMasajed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيمه بنياد شهيد و امور ايثارگران.
        /// </summary>
        public static string MartyrsFoundation {
            get {
                return ResourceManager.GetString("MartyrsFoundation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کارشناسی ارشد.
        /// </summary>
        public static string MasterDegree {
            get {
                return ResourceManager.GetString("MasterDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ.
        /// </summary>
        public static string Mobalegh {
            get {
                return ResourceManager.GetString("Mobalegh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملا محلی سیستان و بلوچستان.
        /// </summary>
        public static string MollaMahaliSistanBaluchestan {
            get {
                return ResourceManager.GetString("MollaMahaliSistanBaluchestan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رهنی.
        /// </summary>
        public static string Mortgage {
            get {
                return ResourceManager.GetString("Mortgage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مستمر ساعتی.
        /// </summary>
        public static string MostamarSaati {
            get {
                return ResourceManager.GetString("MostamarSaati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نهاد نمایندگی مقام معظم رهبری در امور دانشگاه‌ها.
        /// </summary>
        public static string NahadNamayandegiRahbariDaneshgah {
            get {
                return ResourceManager.GetString("NahadNamayandegiRahbariDaneshgah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نهاد نمایندگی مقام معظم رهبری در نیروهای نظامی و انتظامی.
        /// </summary>
        public static string NahadNamayandegiRahbariNirooha {
            get {
                return ResourceManager.GetString("NahadNamayandegiRahbariNirooha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حافظین نهج البلاغه.
        /// </summary>
        public static string NahjAlBalaghaMemorizers {
            get {
                return ResourceManager.GetString("NahjAlBalaghaMemorizers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برادر زاده.
        /// </summary>
        public static string Nephew {
            get {
                return ResourceManager.GetString("Nephew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هيچکدام.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غیر ایرانی.
        /// </summary>
        public static string NonIranian {
            get {
                return ResourceManager.GetString("NonIranian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوین (مجازی).
        /// </summary>
        public static string NovinMajazi {
            get {
                return ResourceManager.GetString("NovinMajazi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نال.
        /// </summary>
        public static string Null {
            get {
                return ResourceManager.GetString("Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سازمانی.
        /// </summary>
        public static string Organizational {
            get {
                return ResourceManager.GetString("Organizational", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سایر.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پدر و مادر.
        /// </summary>
        public static string Parent {
            get {
                return ResourceManager.GetString("Parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پدری.
        /// </summary>
        public static string Paternal {
            get {
                return ResourceManager.GetString("Paternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فارسی.
        /// </summary>
        public static string Persian {
            get {
                return ResourceManager.GetString("Persian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شخصی.
        /// </summary>
        public static string Private {
            get {
                return ResourceManager.GetString("Private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حافظین قرآن.
        /// </summary>
        public static string QuranMemorizers {
            get {
                return ResourceManager.GetString("QuranMemorizers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيمه کميته امداد.
        /// </summary>
        public static string ReliefCommittee {
            get {
                return ResourceManager.GetString("ReliefCommittee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت هیأت مذهبی.
        /// </summary>
        public static string ReligiousCommittees {
            get {
                return ResourceManager.GetString("ReligiousCommittees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت موسسات دینی.
        /// </summary>
        public static string ReligiousInstitutions {
            get {
                return ResourceManager.GetString("ReligiousInstitutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اجاره ای یا رهنی.
        /// </summary>
        public static string RentalOrMortgage {
            get {
                return ResourceManager.GetString("RentalOrMortgage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحقیق.
        /// </summary>
        public static string Research {
            get {
                return ResourceManager.GetString("Research", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پروژه پژوهشی.
        /// </summary>
        public static string ResearchProject {
            get {
                return ResourceManager.GetString("ResearchProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to روحانی مستقر.
        /// </summary>
        public static string RohaniMostaghar {
            get {
                return ResourceManager.GetString("RohaniMostaghar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيمه روستايي.
        /// </summary>
        public static string RuralInsurance {
            get {
                return ResourceManager.GetString("RuralInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سفیران هدایت.
        /// </summary>
        public static string SafiranHedayat {
            get {
                return ResourceManager.GetString("SafiranHedayat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سایر سازمان‌ها و نهادهای رسمی کشور با تأیید کمیسیون.
        /// </summary>
        public static string SayerNahadhaBaTaeidKomision {
            get {
                return ResourceManager.GetString("SayerNahadhaBaTaeidKomision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سازمان حج و زیارت.
        /// </summary>
        public static string SazmanHajVaZiarat {
            get {
                return ResourceManager.GetString("SazmanHajVaZiarat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سازمان اوقاف و امور خیریه.
        /// </summary>
        public static string SazmanOghafVaOmourKheirieh {
            get {
                return ResourceManager.GetString("SazmanOghafVaOmourKheirieh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سازمان تبلیغات اسلامی.
        /// </summary>
        public static string SazmanTablighatEslami {
            get {
                return ResourceManager.GetString("SazmanTablighatEslami", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دبیرخانه شورای برنامه ریزی اهل سنت.
        /// </summary>
        public static string SecretariatOfSunniPlanningCouncil {
            get {
                return ResourceManager.GetString("SecretariatOfSunniPlanningCouncil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خويش فرما.
        /// </summary>
        public static string SelfEmployed {
            get {
                return ResourceManager.GetString("SelfEmployed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ستاد اقامه نماز.
        /// </summary>
        public static string SetadAghameNamaz {
            get {
                return ResourceManager.GetString("SetadAghameNamaz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شریکی.
        /// </summary>
        public static string SharedOwnership {
            get {
                return ResourceManager.GetString("SharedOwnership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شیعه.
        /// </summary>
        public static string Shia {
            get {
                return ResourceManager.GetString("Shia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شورای سیاست‌گذاری ائمه جمعه و نمایندگان ولی فقیه.
        /// </summary>
        public static string ShorayeSiasatgozariEmameJome {
            get {
                return ResourceManager.GetString("ShorayeSiasatgozariEmameJome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خواهر برادر.
        /// </summary>
        public static string Siblings {
            get {
                return ResourceManager.GetString("Siblings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجرد.
        /// </summary>
        public static string Single {
            get {
                return ResourceManager.GetString("Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيمه تامين اجتماعي.
        /// </summary>
        public static string SocialSecurity {
            get {
                return ResourceManager.GetString("SocialSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to همسر.
        /// </summary>
        public static string Spouse {
            get {
                return ResourceManager.GetString("Spouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سنی.
        /// </summary>
        public static string Sunni {
            get {
                return ResourceManager.GetString("Sunni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حمایتی.
        /// </summary>
        public static string Supportive {
            get {
                return ResourceManager.GetString("Supportive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طرح هجرت بلند مدت.
        /// </summary>
        public static string TarhHejratBolandModat {
            get {
                return ResourceManager.GetString("TarhHejratBolandModat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وزارت فرهنگ و ارشاد اسلامی.
        /// </summary>
        public static string VezaratFarhangErshad {
            get {
                return ResourceManager.GetString("VezaratFarhangErshad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيمه بهزيستي.
        /// </summary>
        public static string WelfareInsurance {
            get {
                return ResourceManager.GetString("WelfareInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فوت همسر.
        /// </summary>
        public static string Widowed {
            get {
                return ResourceManager.GetString("Widowed", resourceCulture);
            }
        }
    }
}
